language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - docker build -t trdg .
install:
  - pip install codecov
script:
  - docker run -v $(pwd):/app/ -it trdg:latest coverage run tests.py
  - codecov
